export type Department = "Technology" | "Design" | "Marketing" | "Customer Support" | "Operations" | "Finance" | "Legal" | "People & HR";
export type JobType = "Full-time" | "Part-time" | "Contract" | "Internship";
export type ExperienceLevel = "Junior" | "Mid-level" | "Senior" | "Lead / Manager";
export type OfficeLocation = "Remote" | "Tallinn, Estonia" | "Riga, Latvia" | "Vilnius, Lithuania" | "London, UK";

export type Job = {
  id: string;
  title: string;
  department: Department;
  locations: OfficeLocation[];
  jobType: JobType;
  level: ExperienceLevel;
  salaryMin: number;
  salaryMax: number;
  skills: string[];
  shortDescription: string;
  longDescription: string;
  whatYoullDo: string[];
  requirements: string[];
  niceToHave: string[];
  postedDaysAgo: number;
};

export const WHAT_WE_OFFER = [
  "Remote-first, flexible working culture",
  "Competitive salary with performance bonuses",
  "Comprehensive health & dental insurance",
  "€1,500/year personal learning & development budget",
  "28 days paid holiday + public holidays",
  "Stock option plan for senior roles",
  "Home office setup allowance (€500)",
  "Team retreats twice a year across the Baltics",
];

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const raw: Omit<Job, "id">[] = [
  // Technology (8)
  {
    title: "Senior Full Stack Developer",
    department: "Technology",
    locations: ["Remote", "Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 3000, salaryMax: 5000,
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript", "AWS"],
    shortDescription: "Own end-to-end features on our platform — from API design to polished UI. You'll shape the technical direction of a fast-growing Baltic marketplace.",
    longDescription: "We're looking for a Senior Full Stack Developer to join our core product team and help us scale SkillBuddy to millions of users across the Baltics and beyond. You'll work on everything from API architecture to customer-facing features, partnering closely with designers, product managers, and other engineers to ship impactful work.",
    whatYoullDo: [
      "Design, build, and maintain scalable back-end services using Node.js and PostgreSQL",
      "Build responsive, accessible React interfaces with a focus on performance",
      "Collaborate with product and design on feature specs and technical feasibility",
      "Write clean, well-tested code with CI/CD pipelines",
      "Mentor junior engineers and participate in code review culture",
      "Contribute to architectural decisions and system design discussions",
    ],
    requirements: [
      "5+ years of professional full-stack development experience",
      "Proficiency in React (hooks, context, performance optimization)",
      "Strong Node.js/Express API development skills",
      "Comfortable with PostgreSQL, query optimization, and migrations",
      "Experience with cloud platforms (AWS preferred)",
      "Excellent English communication skills",
    ],
    niceToHave: [
      "Familiarity with TanStack Router / React Query",
      "Experience in marketplace or gig-economy products",
      "Contributions to open-source projects",
    ],
    postedDaysAgo: 3,
  },
  {
    title: "React Native Mobile Developer",
    department: "Technology",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 2500, salaryMax: 4000,
    skills: ["React Native", "iOS", "Android", "TypeScript", "Expo"],
    shortDescription: "Build and ship SkillBuddy's iOS and Android apps used by tens of thousands of users across the Baltics.",
    longDescription: "You'll join our mobile team to design, build, and maintain high-quality React Native applications for both iOS and Android. Our apps are the primary way customers interact with SkillBuddy, so your work will have immediate, real-world impact.",
    whatYoullDo: [
      "Develop cross-platform mobile features using React Native and Expo",
      "Implement pixel-perfect UIs based on Figma designs",
      "Integrate RESTful APIs and handle offline-first data sync",
      "Write unit and integration tests for critical features",
      "Collaborate with the backend team on API contracts",
      "Monitor app performance and crash analytics (Sentry, Firebase)",
    ],
    requirements: [
      "3+ years of React Native development experience",
      "Published apps on both App Store and Google Play",
      "Strong knowledge of TypeScript and modern JS patterns",
      "Experience with push notifications, deep links, and background tasks",
      "Familiarity with Expo and EAS Build",
    ],
    niceToHave: [
      "Native module development (Objective-C / Swift / Kotlin)",
      "Experience with Reanimated v3 for complex animations",
      "Knowledge of App Store review guidelines",
    ],
    postedDaysAgo: 5,
  },
  {
    title: "Backend Engineer (Node.js)",
    department: "Technology",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2800, salaryMax: 4500,
    skills: ["Node.js", "Express", "AWS", "PostgreSQL", "Redis"],
    shortDescription: "Design and scale the APIs powering SkillBuddy's marketplace — payments, notifications, matching engine, and more.",
    longDescription: "As a Backend Engineer, you'll own critical platform services including our bidding engine, payment processing integrations, notification pipeline, and provider matching algorithms. You'll work in a microservices environment on AWS with a focus on reliability, security, and performance.",
    whatYoullDo: [
      "Design RESTful and GraphQL APIs consumed by web and mobile clients",
      "Own the bidding and matching engine for our marketplace",
      "Integrate payment providers (Stripe, bank transfers)",
      "Implement real-time features using WebSockets and message queues",
      "Ensure 99.9% uptime through proactive monitoring and alerting",
      "Define and enforce API contracts with frontend teams",
    ],
    requirements: [
      "5+ years of back-end engineering experience",
      "Expert-level Node.js and Express knowledge",
      "Deep understanding of PostgreSQL (indexes, CTEs, transactions)",
      "AWS experience: EC2, RDS, Lambda, SQS, S3",
      "Security-first mindset (OWASP, JWT, rate limiting)",
    ],
    niceToHave: [
      "Experience with Kafka or RabbitMQ",
      "Knowledge of payment gateway integrations",
      "Background in marketplace or two-sided platform businesses",
    ],
    postedDaysAgo: 7,
  },
  {
    title: "DevOps / Cloud Engineer",
    department: "Technology",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 3000, salaryMax: 4800,
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    shortDescription: "Architect and maintain the cloud infrastructure that keeps SkillBuddy running reliably at scale.",
    longDescription: "Join as our DevOps / Cloud Engineer and take ownership of SkillBuddy's infrastructure. You'll build and maintain automated CI/CD pipelines, manage Kubernetes clusters, and ensure our platform scales gracefully as we grow.",
    whatYoullDo: [
      "Design and maintain cloud infrastructure on AWS using Terraform",
      "Manage Kubernetes (EKS) clusters and containerized workloads",
      "Build and optimise CI/CD pipelines (GitHub Actions)",
      "Implement comprehensive monitoring and alerting (Datadog, PagerDuty)",
      "Drive infrastructure security best practices and compliance",
      "Collaborate with developers to improve deployment velocity",
    ],
    requirements: [
      "5+ years in DevOps, SRE, or cloud engineering roles",
      "Expert-level AWS knowledge (IAM, EKS, RDS, CloudFront, S3)",
      "Proficiency with Kubernetes, Helm, and Docker",
      "Infrastructure as Code with Terraform",
      "CI/CD experience (GitHub Actions, Jenkins, or similar)",
    ],
    niceToHave: [
      "AWS Solutions Architect certification",
      "Experience with service mesh (Istio, Linkerd)",
      "FinOps / cloud cost optimisation experience",
    ],
    postedDaysAgo: 2,
  },
  {
    title: "QA Engineer",
    department: "Technology",
    locations: ["Riga, Latvia"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 1800, salaryMax: 2800,
    skills: ["Selenium", "Jest", "Cypress", "Postman", "TestRail"],
    shortDescription: "Ensure SkillBuddy's platform is bug-free and delightful through comprehensive manual and automated testing.",
    longDescription: "As our QA Engineer, you'll be the last line of defence before features reach our users. You'll design test plans, write automated test suites, and work closely with developers to embed quality throughout the development cycle.",
    whatYoullDo: [
      "Write and maintain end-to-end tests using Cypress and Selenium",
      "Create and execute manual test cases for new features",
      "Build API test suites with Postman/Newman",
      "Maintain test documentation and bug reports in TestRail",
      "Participate in sprint planning to identify testability concerns early",
      "Define and track quality metrics and coverage targets",
    ],
    requirements: [
      "3+ years of QA engineering experience",
      "Strong experience with Cypress and/or Selenium",
      "API testing experience (REST, Postman)",
      "Familiarity with Jest for unit test review",
      "Experience working in Agile/Scrum teams",
    ],
    niceToHave: [
      "Performance testing experience (k6, Artillery)",
      "Experience with accessibility testing (axe, WAVE)",
      "ISTQB certification",
    ],
    postedDaysAgo: 10,
  },
  {
    title: "Junior Frontend Developer",
    department: "Technology",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1200, salaryMax: 1800,
    skills: ["HTML", "CSS", "React", "JavaScript", "Git"],
    shortDescription: "Start your career at a fast-growing Baltic tech startup, building real features that thousands of users interact with daily.",
    longDescription: "This is a fantastic opportunity for an ambitious junior developer to grow rapidly inside a product team that moves fast and invests heavily in mentorship. You'll work on real features from day one, with senior developers guiding you every step of the way.",
    whatYoullDo: [
      "Build responsive UI components using React and Tailwind CSS",
      "Fix bugs and improve existing features based on user feedback",
      "Write clear, maintainable code with guidance from seniors",
      "Participate in daily standups and sprint retrospectives",
      "Learn and grow through regular 1-on-1 mentorship sessions",
    ],
    requirements: [
      "Solid understanding of HTML, CSS, and JavaScript fundamentals",
      "Familiarity with React (hooks, props, state)",
      "Basic Git knowledge (branching, pull requests)",
      "Passion for learning and growing as an engineer",
      "Good written English communication skills",
    ],
    niceToHave: [
      "Personal projects or portfolio",
      "Exposure to TypeScript",
      "Familiarity with Tailwind CSS or similar utility-first CSS",
    ],
    postedDaysAgo: 1,
  },
  {
    title: "UI/UX Engineer",
    department: "Technology",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 2000, salaryMax: 3500,
    skills: ["Figma", "React", "CSS", "TypeScript", "Storybook"],
    shortDescription: "Bridge the gap between design and engineering, building our component library and ensuring every pixel is perfect.",
    longDescription: "As our UI/UX Engineer, you'll work at the intersection of design and development — translating Figma designs into production-ready React components, maintaining our design system, and championing accessibility across the platform.",
    whatYoullDo: [
      "Build and maintain a comprehensive Storybook component library",
      "Translate Figma designs to React with pixel-perfect precision",
      "Champion accessibility standards (WCAG 2.1 AA)",
      "Collaborate directly with designers on design token systems",
      "Conduct cross-browser and device compatibility testing",
      "Lead front-end design reviews and provide feedback",
    ],
    requirements: [
      "3+ years of front-end engineering with strong UI focus",
      "Expert CSS knowledge (animations, layout, custom properties)",
      "Proficiency with Figma and design handoff workflows",
      "React and TypeScript experience",
      "Understanding of accessibility and ARIA patterns",
    ],
    niceToHave: [
      "Experience maintaining large-scale design systems",
      "Animation experience with Framer Motion or GSAP",
      "Contribution to open-source UI libraries",
    ],
    postedDaysAgo: 6,
  },
  {
    title: "Mobile App Developer (Flutter)",
    department: "Technology",
    locations: ["Vilnius, Lithuania"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 2500, salaryMax: 4000,
    skills: ["Flutter", "Dart", "Firebase", "REST APIs", "Git"],
    shortDescription: "Build a next-generation Flutter app expanding SkillBuddy into new markets across Central and Eastern Europe.",
    longDescription: "We're expanding our mobile offering with a Flutter-based app targeting new markets in Central Europe. As our Flutter Developer, you'll design the app architecture from the ground up and work closely with our product team to deliver outstanding mobile experiences.",
    whatYoullDo: [
      "Architect and develop a Flutter app for iOS and Android from scratch",
      "Implement BLoC/Riverpod state management patterns",
      "Integrate Firebase services (Auth, Firestore, Cloud Messaging)",
      "Build complex UI animations and custom widgets",
      "Collaborate with UX designers to craft intuitive flows",
      "Write thorough widget tests and integration tests",
    ],
    requirements: [
      "3+ years of Flutter / Dart development",
      "Understanding of mobile app architecture patterns (BLoC, MVVM)",
      "Experience publishing Flutter apps to both stores",
      "Proficiency in REST API integration and JSON serialisation",
    ],
    niceToHave: [
      "Experience with Flutter flavors for multi-environment builds",
      "Familiarity with Fastlane for CI/CD on Flutter",
      "Knowledge of Lithuanian or other Baltic languages",
    ],
    postedDaysAgo: 14,
  },

  // Design (4)
  {
    title: "Senior UI/UX Designer",
    department: "Design",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2000, salaryMax: 3500,
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research", "Design Systems"],
    shortDescription: "Lead the design vision for SkillBuddy's marketplace — shaping experiences that millions of users will love.",
    longDescription: "As our Senior UI/UX Designer, you'll own the end-to-end design process from user research to polished Figma specs. You'll mentor junior designers, champion user-centred thinking, and work hand-in-hand with engineering to ship high-quality experiences.",
    whatYoullDo: [
      "Lead end-to-end UX projects: research, wireframes, prototypes, final designs",
      "Maintain and evolve the SkillBuddy design system in Figma",
      "Conduct user interviews, usability tests, and synthesise findings",
      "Present design rationale confidently to stakeholders",
      "Mentor junior and mid-level designers on the team",
      "Define and track UX quality metrics (task completion rate, SUS scores)",
    ],
    requirements: [
      "5+ years of UI/UX design for digital products",
      "Expert Figma skills including auto-layout, variables, and component sets",
      "Portfolio demonstrating complex product design work",
      "Experience conducting qualitative and quantitative user research",
      "Strong understanding of accessibility (WCAG) principles",
    ],
    niceToHave: [
      "Experience designing two-sided marketplace products",
      "Motion design skills (Principle, Protopie)",
      "Familiarity with front-end implementation (HTML/CSS)",
    ],
    postedDaysAgo: 4,
  },
  {
    title: "Brand & Graphic Designer",
    department: "Design",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 1500, salaryMax: 2500,
    skills: ["Illustrator", "Photoshop", "Figma", "Brand Identity", "Print Design"],
    shortDescription: "Shape the visual voice of SkillBuddy — from social content to campaign visuals to brand guidelines.",
    longDescription: "We're growing our Brand team and looking for a talented Graphic Designer to help us tell the SkillBuddy story through compelling visuals. You'll create everything from social media assets and marketing collateral to brand guidelines and illustration systems.",
    whatYoullDo: [
      "Create social media graphics, paid ad creatives, and email visuals",
      "Maintain and develop SkillBuddy's visual identity guidelines",
      "Design print and digital marketing collateral for campaigns",
      "Create custom illustrations aligned with our brand voice",
      "Collaborate with the marketing team on campaign briefs",
    ],
    requirements: [
      "3+ years of graphic / brand design experience",
      "Expert Adobe Illustrator and Photoshop skills",
      "Strong understanding of typography and layout",
      "Portfolio demonstrating brand consistency across mediums",
      "Ability to manage multiple projects simultaneously",
    ],
    niceToHave: [
      "Animation / motion graphics skills (After Effects)",
      "3D or isometric illustration experience",
      "Experience with Figma for handoff to developers",
    ],
    postedDaysAgo: 8,
  },
  {
    title: "Motion Designer",
    department: "Design",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 1800, salaryMax: 3000,
    skills: ["After Effects", "Lottie", "CSS Animation", "Figma", "Cinema 4D"],
    shortDescription: "Create stunning animations that bring the SkillBuddy brand to life across web, mobile, and social.",
    longDescription: "As our Motion Designer, you'll craft micro-interactions, explainer animations, and campaign videos that make SkillBuddy feel premium and polished. Your work will appear on our website, apps, and across paid and organic social channels.",
    whatYoullDo: [
      "Design and produce Lottie animations for web and mobile apps",
      "Create video ads, social reels, and explainer content",
      "Collaborate with product designers on UI micro-interactions",
      "Build a library of reusable motion components and principles",
      "Work to tight campaign deadlines without compromising quality",
    ],
    requirements: [
      "3+ years of professional motion design experience",
      "Expert After Effects skills with strong principles knowledge",
      "Experience exporting Lottie animations for production use",
      "Understanding of CSS animation for developer handoff",
      "Strong portfolio of work across digital and social formats",
    ],
    niceToHave: [
      "3D motion experience (Cinema 4D, Blender)",
      "Video editing skills (Premiere Pro, DaVinci Resolve)",
      "Experience in app onboarding or interactive animation",
    ],
    postedDaysAgo: 12,
  },
  {
    title: "Product Designer",
    department: "Design",
    locations: ["Riga, Latvia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2200, salaryMax: 3800,
    skills: ["User Research", "Figma", "Design Systems", "Prototyping", "A/B Testing"],
    shortDescription: "Drive the product design of key platform areas, from discovery to launch, with a deep focus on user outcomes.",
    longDescription: "As a Product Designer at SkillBuddy, you'll be embedded in one of our core product squads, owning the design of a critical platform area. You'll partner closely with product managers and engineers to identify problems, design solutions, and measure outcomes.",
    whatYoullDo: [
      "Own design for a core product area end-to-end",
      "Run discovery workshops, user interviews, and concept testing",
      "Create detailed Figma specs and interactive prototypes",
      "Define and analyse product metrics alongside data analysts",
      "Run A/B tests on key user flows and iterate on results",
      "Build components that contribute to the broader design system",
    ],
    requirements: [
      "5+ years of product design experience in digital products",
      "Strong systems thinking and ability to design at scale",
      "Expert Figma with advanced prototyping",
      "Experience running user research and synthesising insights",
      "Data-informed design approach with A/B testing experience",
    ],
    niceToHave: [
      "Background in marketplace or platform products",
      "Familiarity with SQL for self-serve data analysis",
      "Experience with Design Thinking facilitation",
    ],
    postedDaysAgo: 9,
  },

  // Marketing (3)
  {
    title: "Digital Marketing Manager",
    department: "Marketing",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2000, salaryMax: 3500,
    skills: ["SEO", "SEM", "Google Analytics", "Meta Ads", "Email Marketing"],
    shortDescription: "Lead SkillBuddy's performance marketing — driving customer acquisition and provider growth across all paid and organic channels.",
    longDescription: "We're looking for a data-driven Digital Marketing Manager to lead our growth channels. You'll own the full-funnel marketing strategy from SEO and paid search to email campaigns and affiliate partnerships — with a clear mandate to grow our user base across the Baltics.",
    whatYoullDo: [
      "Own and optimise performance marketing channels (Google, Meta, TikTok)",
      "Lead SEO strategy: technical audits, content planning, link building",
      "Plan and execute email marketing campaigns with A/B testing",
      "Analyse campaign performance and report to leadership weekly",
      "Manage marketing budget allocation and optimise CAC and ROAS",
      "Identify and test new growth channels proactively",
    ],
    requirements: [
      "5+ years of digital marketing experience",
      "Hands-on experience with Google Ads, Meta Ads, and analytics",
      "Proven SEO expertise (technical and content)",
      "Strong analytical mindset with proficiency in Google Analytics / GA4",
      "Experience managing significant advertising budgets (€10k+/month)",
    ],
    niceToHave: [
      "Experience marketing a marketplace or platform product",
      "Knowledge of Baltic markets (Estonian, Latvian, Lithuanian)",
      "Google Ads or HubSpot certification",
    ],
    postedDaysAgo: 15,
  },
  {
    title: "Social Media Specialist",
    department: "Marketing",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1200, salaryMax: 2000,
    skills: ["Content Creation", "Instagram", "TikTok", "Canva", "Copywriting"],
    shortDescription: "Grow SkillBuddy's presence on Instagram, TikTok, and LinkedIn with creative content that engages our community.",
    longDescription: "As our Social Media Specialist, you'll manage and grow SkillBuddy's presence across Instagram, TikTok, Facebook, and LinkedIn. You'll create, schedule, and analyse content that resonates with both customers looking for help and skilled professionals wanting to earn more.",
    whatYoullDo: [
      "Create and schedule organic content across all major social platforms",
      "Produce short-form video content for TikTok and Instagram Reels",
      "Respond to comments and DMs to build community engagement",
      "Track social KPIs and provide weekly performance reports",
      "Collaborate with the Brand Designer on campaign visuals",
      "Identify trends and translate them into relevant SkillBuddy content",
    ],
    requirements: [
      "1-2 years managing social media for a brand (not just personal)",
      "Strong copywriting skills in English (Estonian/Latvian a bonus)",
      "Comfortable creating short-form video content independently",
      "Familiarity with scheduling tools (Buffer, Sprout Social)",
      "Understanding of social analytics and what metrics matter",
    ],
    niceToHave: [
      "Experience with influencer outreach and UGC campaigns",
      "Basic photo and video editing skills",
      "Familiarity with LinkedIn B2B content strategy",
    ],
    postedDaysAgo: 3,
  },
  {
    title: "Content Writer (Multilingual)",
    department: "Marketing",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1000, salaryMax: 1800,
    skills: ["English", "Estonian", "Latvian", "Lithuanian", "SEO Writing"],
    shortDescription: "Create compelling content in multiple Baltic languages that helps SkillBuddy rank higher and convert better.",
    longDescription: "We need a talented multilingual Content Writer to produce SEO-optimised blog posts, landing page copy, email templates, and help centre articles across our five markets. You'll work closely with the Digital Marketing Manager to align content with our keyword and conversion strategy.",
    whatYoullDo: [
      "Write SEO-optimised blog articles (2-3 per week) for multiple markets",
      "Translate and adapt marketing copy from English into ET, LV, LT, RU",
      "Draft and refine landing page copy for new feature launches",
      "Write help centre articles and FAQs for the support team",
      "Conduct keyword research and optimise existing content",
      "Maintain a consistent brand voice across all written materials",
    ],
    requirements: [
      "Fluency in English plus at least one Baltic language (ET/LV/LT)",
      "Strong writing and editing skills across multiple formats",
      "Basic understanding of SEO principles and keyword optimisation",
      "Ability to manage multiple deadlines simultaneously",
    ],
    niceToHave: [
      "Fluency in Russian for the RU market",
      "Experience with CMS tools (WordPress, Webflow, Contentful)",
      "Familiarity with Ahrefs or Semrush for keyword research",
    ],
    postedDaysAgo: 20,
  },

  // Customer Support (4)
  {
    title: "Customer Support Lead",
    department: "Customer Support",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 1800, salaryMax: 2500,
    skills: ["CRM", "Zendesk", "Leadership", "SLA Management", "Process Design"],
    shortDescription: "Build and lead SkillBuddy's customer support team, setting the standard for service quality across all markets.",
    longDescription: "As Customer Support Lead, you'll manage a team of support agents across three countries, define support processes, own our Zendesk configuration, and ensure every customer gets a fast, friendly, and effective resolution.",
    whatYoullDo: [
      "Lead, coach, and grow a team of 8+ multilingual support agents",
      "Define, monitor, and report on SLA, CSAT, and resolution metrics",
      "Manage and optimise our Zendesk helpdesk configuration",
      "Create knowledge bases, macros, and escalation workflows",
      "Work cross-functionally with product to reduce ticket volume",
      "Handle escalated complex cases and high-profile clients",
    ],
    requirements: [
      "4+ years in customer support with 2+ years in a leadership role",
      "Experience managing Zendesk (or similar) at scale",
      "Proven ability to hire, train, and retain support talent",
      "Strong English communication; additional Baltic language a bonus",
      "Data-driven approach to support operations",
    ],
    niceToHave: [
      "Experience in marketplace or two-sided platform businesses",
      "Background in high-growth startup environments",
      "Knowledge of AI/chatbot integration for support automation",
    ],
    postedDaysAgo: 11,
  },
  {
    title: "Support Agent (Estonian/English)",
    department: "Customer Support",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1000, salaryMax: 1500,
    skills: ["Communication", "Problem Solving", "Zendesk", "Estonian", "English"],
    shortDescription: "Be the friendly, helpful face of SkillBuddy for our Estonian customers — resolving issues with speed and empathy.",
    longDescription: "We're looking for a customer-focused Support Agent to join our Tallinn team. You'll be the first point of contact for Estonian and English-speaking customers, handling enquiries via chat, email, and phone, and working to resolve issues quickly and professionally.",
    whatYoullDo: [
      "Respond to customer enquiries via live chat, email, and phone",
      "Resolve billing, booking, and account issues in a timely manner",
      "Escalate complex technical issues to the right internal teams",
      "Document common issues to improve our help centre content",
      "Meet and exceed SLA and CSAT targets",
    ],
    requirements: [
      "Native or C1+ Estonian and strong English communication skills",
      "Customer service or support experience preferred (but not required)",
      "Empathetic, patient, and solution-oriented mindset",
      "Comfortable using support tools (Zendesk training provided)",
    ],
    niceToHave: [
      "Experience in a marketplace or tech company support role",
      "Russian language skills for additional market coverage",
    ],
    postedDaysAgo: 2,
  },
  {
    title: "Support Agent (Russian/Latvian)",
    department: "Customer Support",
    locations: ["Riga, Latvia"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1000, salaryMax: 1500,
    skills: ["Russian", "Latvian", "CRM", "Communication", "English"],
    shortDescription: "Support our Russian and Latvian-speaking customers from our Riga office with friendly, effective service.",
    longDescription: "We need a Russian and Latvian-speaking Support Agent based in Riga to serve our growing Latvian customer base. You'll handle enquiries across all channels, ensuring Latvian and Russian-speaking customers get the same outstanding experience as all other markets.",
    whatYoullDo: [
      "Handle customer enquiries in Russian, Latvian, and English",
      "Resolve booking, payment, and account-related issues",
      "Collaborate with the Tallinn support team on escalations",
      "Contribute translations for help centre articles",
      "Monitor and report on market-specific support trends",
    ],
    requirements: [
      "Fluency in Russian and Latvian (native or near-native)",
      "Good written and spoken English",
      "Customer-focused and patient communication style",
      "Basic computer skills and willingness to learn support tools",
    ],
    niceToHave: [
      "Familiarity with Zendesk or similar CRM tools",
      "Previous customer service experience",
    ],
    postedDaysAgo: 4,
  },
  {
    title: "Support Agent (Lithuanian)",
    department: "Customer Support",
    locations: ["Vilnius, Lithuania"],
    jobType: "Full-time",
    level: "Junior",
    salaryMin: 1000, salaryMax: 1500,
    skills: ["Lithuanian", "Customer Service", "English", "Zendesk", "CRM"],
    shortDescription: "Deliver excellent support for our Lithuanian customers from our Vilnius hub.",
    longDescription: "As our Lithuania Support Agent, you'll be the primary contact for Lithuanian-speaking customers and service providers. Based in our Vilnius office, you'll work alongside a small team to deliver fast, friendly support while contributing to our Lithuanian help content.",
    whatYoullDo: [
      "Handle Lithuanian customer enquiries via chat, email, and phone",
      "Resolve service booking issues, disputes, and payment questions",
      "Translate and improve help centre content into Lithuanian",
      "Escalate complex issues appropriately and follow up to closure",
      "Share market-specific insights with the broader team",
    ],
    requirements: [
      "Native Lithuanian speaker with professional written proficiency",
      "English communication at B2 level or above",
      "Positive, people-first attitude and strong problem-solving skills",
      "Willingness to learn and use support tools (full training provided)",
    ],
    niceToHave: [
      "Knowledge of Russian for additional customer coverage",
      "Previous experience in customer-facing roles",
    ],
    postedDaysAgo: 6,
  },

  // Operations (2)
  {
    title: "Operations Manager",
    department: "Operations",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2500, salaryMax: 4000,
    skills: ["Process Optimisation", "Leadership", "Data Analysis", "OKRs", "Project Management"],
    shortDescription: "Drive operational excellence across SkillBuddy — streamlining processes, managing vendors, and enabling the team to scale.",
    longDescription: "As Operations Manager, you'll be the backbone of SkillBuddy's operational efficiency. You'll identify and eliminate operational bottlenecks, manage vendor relationships, oversee cross-team projects, and build the systems and processes that allow us to scale sustainably.",
    whatYoullDo: [
      "Audit existing processes and identify opportunities for automation and improvement",
      "Manage relationships with key operational vendors and partners",
      "Lead cross-functional operational projects from scoping to delivery",
      "Build and maintain operational dashboards and KPI tracking",
      "Partner with finance on budgeting and cost control initiatives",
      "Support hiring processes and onboarding for new team members",
    ],
    requirements: [
      "5+ years in operations management or business operations",
      "Proven track record of process improvement at scale",
      "Strong analytical skills with proficiency in Excel/Google Sheets",
      "Experience leading cross-functional projects without direct authority",
      "Excellent stakeholder management and communication skills",
    ],
    niceToHave: [
      "Experience in a marketplace or tech startup environment",
      "Knowledge of ERP or project management tools (Notion, Asana, Monday)",
      "MBA or relevant postgraduate qualification",
    ],
    postedDaysAgo: 18,
  },
  {
    title: "Business Analyst",
    department: "Operations",
    locations: ["Remote"],
    jobType: "Full-time",
    level: "Mid-level",
    salaryMin: 2000, salaryMax: 3200,
    skills: ["Data Analysis", "SQL", "Excel", "Tableau", "Requirements Gathering"],
    shortDescription: "Turn SkillBuddy's data into insights that drive better product, marketing, and operational decisions.",
    longDescription: "As a Business Analyst, you'll bridge the gap between data and decision-making at SkillBuddy. You'll work across teams to gather requirements, analyse data, and present actionable insights that influence product roadmaps, marketing strategies, and operational improvements.",
    whatYoullDo: [
      "Write SQL queries to extract, clean, and analyse business data",
      "Build and maintain dashboards in Tableau or similar tools",
      "Document business requirements for new product and operations initiatives",
      "Conduct market research and competitive benchmarking",
      "Present data-driven recommendations to leadership",
      "Support A/B test analysis and statistical interpretation",
    ],
    requirements: [
      "3+ years as a Business Analyst or Data Analyst",
      "Strong SQL skills (complex joins, window functions, CTEs)",
      "Experience building dashboards in Tableau, Looker, or Power BI",
      "Strong written and verbal communication skills in English",
      "Ability to translate business questions into analytical frameworks",
    ],
    niceToHave: [
      "Python or R for advanced statistical analysis",
      "Experience with dbt or data modelling",
      "Background in marketplace analytics",
    ],
    postedDaysAgo: 22,
  },

  // Finance (1)
  {
    title: "Financial Controller",
    department: "Finance",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2500, salaryMax: 4000,
    skills: ["Accounting", "IFRS", "Forecasting", "Excel", "Xero"],
    shortDescription: "Own SkillBuddy's financial reporting, control environment, and planning as we scale across multiple markets.",
    longDescription: "As Financial Controller, you'll lead our financial reporting, ensure compliance across five markets, manage the monthly close process, and partner with the CEO and leadership team on financial planning and analysis. This is a senior individual contributor role with a path to CFO.",
    whatYoullDo: [
      "Own the monthly, quarterly, and annual financial close process",
      "Prepare IFRS-compliant financial statements and management accounts",
      "Build and maintain multi-currency financial models and forecasts",
      "Manage relationships with auditors, tax advisors, and banks",
      "Implement and improve internal financial controls and policies",
      "Partner with business leaders on budget management and cost control",
    ],
    requirements: [
      "5+ years of financial controlling or senior finance experience",
      "ACCA, CIMA, or equivalent professional accounting qualification",
      "IFRS and multi-entity consolidation experience",
      "Advanced Excel / Google Sheets financial modelling",
      "Experience with accounting software (Xero, QuickBooks, or SAP)",
    ],
    niceToHave: [
      "Experience in a venture-backed tech startup",
      "Knowledge of Estonian or Baltic tax regulations",
      "Familiarity with Stripe/payment reconciliation processes",
    ],
    postedDaysAgo: 30,
  },

  // Legal (1)
  {
    title: "Legal Counsel (EU)",
    department: "Legal",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 3000, salaryMax: 5000,
    skills: ["EU Law", "GDPR", "Contract Negotiation", "Employment Law", "Corporate Law"],
    shortDescription: "Provide strategic legal counsel as SkillBuddy navigates rapid growth, new markets, and complex regulatory environments.",
    longDescription: "As our first in-house Legal Counsel, you'll handle a broad and exciting remit — from GDPR compliance and marketplace terms to employment law, vendor contracts, and expansion into new EU markets. You'll work directly with the founders and leadership team.",
    whatYoullDo: [
      "Draft, review, and negotiate commercial contracts with vendors, partners, and enterprise clients",
      "Ensure GDPR compliance across all products and operational processes",
      "Advise on employment law matters across Estonia, Latvia, Lithuania",
      "Lead legal due diligence for potential partnerships and investments",
      "Manage relationships with external law firms across EU jurisdictions",
      "Develop and maintain internal legal policies and templates",
    ],
    requirements: [
      "7+ years of legal experience in EU commercial law",
      "Qualified lawyer in at least one EU jurisdiction",
      "Deep expertise in GDPR and EU data protection regulation",
      "Experience with startup, tech, or platform company legal work",
      "Fluent English; Estonian or another Baltic language a significant plus",
    ],
    niceToHave: [
      "Experience advising on marketplace or gig-economy legal structures",
      "Familiarity with Estonian e-Residency and company law",
      "Background in venture-backed company legal work",
    ],
    postedDaysAgo: 45,
  },

  // People & HR (1)
  {
    title: "HR Manager",
    department: "People & HR",
    locations: ["Tallinn, Estonia"],
    jobType: "Full-time",
    level: "Senior",
    salaryMin: 2000, salaryMax: 3500,
    skills: ["Recruitment", "People Ops", "Culture", "Performance Management", "HRIS"],
    shortDescription: "Build the people operations function at SkillBuddy — from talent acquisition to culture, learning, and employee experience.",
    longDescription: "As our first dedicated HR Manager, you'll establish SkillBuddy's people operations from the ground up. You'll own the entire employee lifecycle — from attracting top talent to onboarding, performance management, learning & development, and building a culture that allows our diverse, distributed team to do their best work.",
    whatYoullDo: [
      "Lead full-cycle recruiting across all departments and seniority levels",
      "Design and manage a structured onboarding programme",
      "Build and own our performance review and feedback processes",
      "Develop L&D initiatives and manage the learning budget",
      "Ensure compliance with employment law in all operating markets",
      "Champion SkillBuddy's culture and employee engagement initiatives",
    ],
    requirements: [
      "5+ years of HR experience, ideally in a tech or startup environment",
      "Proven ability to build HR processes from scratch",
      "Experience with HRIS tools (BambooHR, Personio, or similar)",
      "Strong knowledge of employment law in Estonia",
      "Excellent interpersonal and communication skills in English",
    ],
    niceToHave: [
      "HR experience across multiple EU countries",
      "Experience setting up employee share option plans (ESOPs)",
      "CIPD or equivalent HR qualification",
    ],
    postedDaysAgo: 7,
  },
];

export const JOBS: Job[] = raw.map((j, i) => ({
  ...j,
  id: slugify(j.title),
}));

export function getJob(idOrSlug: string): Job | undefined {
  return JOBS.find((j) => j.id === idOrSlug);
}

export const DEPARTMENTS: Department[] = ["Technology", "Design", "Marketing", "Customer Support", "Operations", "Finance", "Legal", "People & HR"];

export const OFFICE_LOCATIONS: OfficeLocation[] = ["Remote", "Tallinn, Estonia", "Riga, Latvia", "Vilnius, Lithuania", "London, UK"];

export const DEPT_COLORS: Record<Department, string> = {
  "Technology": "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  "Design": "bg-purple-500/15 text-purple-600 dark:text-purple-400",
  "Marketing": "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  "Customer Support": "bg-teal-500/15 text-teal-600 dark:text-teal-400",
  "Operations": "bg-slate-500/15 text-slate-600 dark:text-slate-400",
  "Finance": "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  "Legal": "bg-red-500/15 text-red-600 dark:text-red-400",
  "People & HR": "bg-pink-500/15 text-pink-600 dark:text-pink-400",
};

export const JOB_TYPE_COLORS: Record<JobType, string> = {
  "Full-time": "bg-primary/15 text-primary",
  "Part-time": "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  "Contract": "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  "Internship": "bg-purple-500/15 text-purple-600 dark:text-purple-400",
};
